# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
import sphinx_theme
sys.path.insert(0, os.path.abspath('../..'))
import autowinpy

# -- Project information -----------------------------------------------------

project = 'autowinpy'
copyright = '2019, soma0sd'
author = 'soma0sd'

# The full version, including alpha/beta/rc tags
release = autowinpy.__version__


# -- General configuration ---------------------------------------------------

extensions = [
  'sphinx.ext.napoleon',
  'sphinx.ext.autosummary',
  'sphinx.ext.viewcode'
]
napoleon_google_docstring = True
napoleon_numpy_docstring = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ko'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
# neo_rtd_theme
html_theme = 'neo_rtd_theme'
# html_theme = 'stanford_theme'
html_theme_path = ["_themes/sphinx_theme", ]
html_css_files = [
  'style.css'
]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_search_language = "ko"
